"""empty message

Revision ID: 4484f4ca7ac3
Revises: 
Create Date: 2020-07-18 23:52:08.839850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4484f4ca7ac3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_template')
    # ### end Alembic commands ###
